### PR TITLE
Update dependencies and bump from 1.5.0 to 1.5.1

### PR DESCRIPTION
**Pull request by lehmannk**
updated ruby, grpc and web_socket_channel packages

### CODE REVIEW

**Comment by fzyzcjy** [comment]
For the macos ci error: looks like it is because `maxim-lobanov/setup-cocoapods@v1`, more specifically

```
ERROR:  Error installing cocoapods:
	The last version of activesupport (>= 5.0, < 8) to support your Ruby & RubyGems was 7.1.4.1. Try installing it with `gem install activesupport -v 7.1.4.1` and then running the current command again
	activesupport requires Ruby version >= 3.1.0. The current ruby version is 2.7.8.225.
```

I guess searching that may help.

**Comment by fzyzcjy** [comment]
@all-contributors please add @lehmannk for code

**Comment by fzyzcjy** [comment]
Btw, no worries about bumping versions - the release script will do so automatically

**Comment by fzyzcjy** [comment]
I am a bit confused, it seems only repo owner can create releases

**Comment by lehmannk** [comment]
so even you as admin cannot trigger a new release to reflect current master ?



Am Montag, 19. Mai 2025 um 09:59:16 +02:00, hat fzyzcjy ***@***.***> geschrieben:

**Comment by fzyzcjy** [comment]
I can trigger one (thought you meant you could trigger a release before). I will release a bit later.

**Comment by fzyzcjy** [comment]
I will release it tomorrow (created github release but the pub publish has a bit of issue and I will find time tomorrow for it)

**Comment by fzyzcjy** [comment]
done

**Pull request merged**
