### PR TITLE
simple code QA for a better scoring 

### PR DESCRIPTION
**Pull request by meltzow**
"we" want to have a full scoring. see https://pub.dev/packages/convenient_test/score ;-)

### CODE REVIEW

**Comment by meltzow** [comment]
oh we are using a line-length with 120 in our checks. It looks like, it's more as the checker for the pub.dev-scoring is using.   
ok than I will revert my formatting things.

**Comment by meltzow** [comment]
just only 5 points more ;-) 
because of removing insecure link in Readme.md

**Comment by meltzow** [comment]
> > oh we are using a line-length with 120 in our checks. It looks like, it's more as the checker for the pub.dev-scoring is using.
> > ok than I will revert my formatting things.
> 
> No worries, we can format it to be 80. Indeed I have done so for https://github.com/fzyzcjy/flutter_rust_bridge for the pub scores (though I personally prefer 120).

this check will be failed if we format it to be 80:      https://github.com/fzyzcjy/flutter_convenient_test/blob/582bf4873783c58f46ffdeba2baaacbc3138c746/.github/workflows/ci.yaml#L53

**Comment by meltzow** [comment]
grrr ... this was a huge refactoring in a lot of files. the score-page (https://pub.dev/packages/convenient_test/score) displays formatting warnings in only 2 files. But after I started the reformatting in these 2 files, the CI failed. 
Luckily it was a automatically done with a combination of "flutter analyze", "dart format . " and "dart fix --apply" 
Please decide by your own, if this PR is needed and merged

**Comment by fzyzcjy** [comment]
> this check will be failed if we format it to be 80

Just change the CI :)

**Comment by fzyzcjy** [comment]
@all-contributors please add @meltzow for code

**Pull request merged**
