### PR TITLE
Fix deprecation warnings

### PR DESCRIPTION
**Pull request by madmini**
Follow up to #355, to fix the left-over deprecation warnings and update the build scripts (as generated by flutter).

This may fix some red pipelines.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Looks great, feel free to ping me when everything is done!

**Comment by madmini** [comment]
For now I cant even get the example to build 😅

so, feel free to merge, I will create another PR if I get around to it

**Comment by fzyzcjy** [comment]
I will check it now

**Comment by fzyzcjy** [comment]
I can run the demo locally; the CI is also happy (except for 0.10% golden diff errors - which I guess happens due to different environments and minor versions to execute golden... so not a real problem since humans cannot realize the picture difference).

> For now I cant even get the example to build 

May I know a bit more details?

image

**Pull request merged**
