### PR TITLE
💚 Fix CI x2

### PR DESCRIPTION
**Pull request by AlexV525**

### CODE REVIEW

**Comment by AlexV525** [comment]
Hmm, more errors coming in. I should now grab my PC to fix them.

**Comment by fzyzcjy** [comment]
Think so. Take your time!

**Comment by AlexV525** [comment]
Should we keep the Flutter 3.0.0 test?

**Comment by fzyzcjy** [comment]
> Should we keep the Flutter 3.0.0 test?

Given 3.3 is around for a while, maybe we can remove 3.0

**Comment by AlexV525** [comment]
Not passed tests require a new version of `convenient_test_common_dart` published.

Can you do a squash merge instead of a merge commit? 😄

**Comment by fzyzcjy** [comment]
Sure :)

**Pull request merged**
