### PR TITLE
fix: flag to prevent pumpAndSettle for other commands

### PR DESCRIPTION
**Pull request by ostk0069**
https://github.com/fzyzcjy/flutter_convenient_test/pull/252 add flag to prevent pumpAndSettle.
This should be added to other TFinderCommand as well.

### CODE REVIEW

**Review by fzyzcjy — APPROVED** [review]
Will merge once CI passes :)

**Comment by fzyzcjy** [comment]
Well, wait a bit for #269

**Comment by ostk0069** [comment]
@fzyzcjy Thank you for fixing CI. looks all green.

**Comment by fzyzcjy** [comment]
Good job

**Comment by fzyzcjy** [comment]
@all-contributors please add @ostk0069 for code

**Pull request merged**
