### PR TITLE
Refactor secondary panel tab bar

### PR DESCRIPTION
**Pull request by gilice**
This now:
- is a widget instead of a function (see #320)
- uses Flutter's builtin ToggleButtons instead of a custom implementation

### CODE REVIEW

**Comment by gilice** [comment]
@fzyzcjy btw should I make small PRS like this or larger ones?

**Comment by fzyzcjy** [comment]
> @fzyzcjy btw should I make small PRS like this or larger ones?

Smaller PRs are much easier to review and gets merged more quickly, and Flutter repo strongly recommengs using smaller PRs. So yes, your small PRs are good!

**Comment by fzyzcjy** [comment]
However, if multi PRs are doing the same series of thing, e.g. "refactor `buildSomething` into its own widget", then IMHO we can make it one PR instead of a dozen PRs

**Comment by fzyzcjy** [comment]
Good job :) merged

**Pull request merged**
