### PR TITLE
Remove generated files and update .gitignore

### PR DESCRIPTION
**Pull request by madmini**
added some relevant .gitignore entries from https://github.com/flutter/flutter/blob/master/.gitignore

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Good job! However, I am not sure whether that is the best way. For example, in https://github.com/flutter/flutter/issues/13892 there seems to be many possible gitignores. Could you please check whether those entries are all suggested to be there or not?

**Comment by madmini** [comment]
As the discussion in the linked issue seems to indicate, there is no canonical `.gitignore`. I believe the one from the main flutter repo may be the closest thing to a complete `.gitignore`.

As for the entries I copied from there, flutter/flutter#13554 (and the corresponding merged PR) says that these are not intended to be checked in.
In addition, each of these files has a header that says `Generated file, do not edit.` and is regenerated when running or building the apps.

**Comment by fzyzcjy** [comment]
Looks reasonable!

**Comment by fzyzcjy** [comment]
@all-contributors please add @madmini for code

**Pull request merged**
