### PR TITLE
Added Linux CI

### PR DESCRIPTION
**Pull request by ethancadoo**

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Good job! I have clicked the "run ci" (a limitation by github - must manually click for first-time contributor)

**Comment by ethancadoo** [comment]
Looks all good on my side! I had to change the directory structure within the tar output but now everything looks great!

**Comment by fzyzcjy** [comment]
I do not have a linux computer at my hand. So could you please check the artifact: https://github.com/fzyzcjy/flutter_convenient_test/actions/runs/2879515356 "manager_linux" file, does it work on your machine after downloading and using it?

**Comment by fzyzcjy** [comment]
@all-contributors please add @ethancadoo for code

**Comment by SherlockShoe** [comment]
Yes it works on Ubuntu 20.04 as long as you run
`sudo apt install libvlc-dev vlc gcc libstdc++6 -y`

**Comment by SherlockShoe** [comment]
@ethancadoo Is me as well, I accidentally mixed work and personal git.

**Comment by fzyzcjy** [comment]
LGTM, good job!

**Comment by fzyzcjy** [comment]
@all-contributors please add @ethancadoo for code

**Pull request merged**
